### ISSUE TITLE
A mistake in compile this code

### ISSUE THREAD

**Issue by 466152112** [ChenglongChen/Kaggle_CrowdFlower#1]
你好。我在编译的时候遇到了下面的错误，请问我是那个地方每配置好吗？

[zhouge@fly Feat]$ python run_all.py
Load data...
Done.
Pre-process data...
./preprocess.py:54: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  dfTrain["median_relevance_%d" % (i+1)][dfTrain["median_relevance"]==(i+1)] = 1
Traceback (most recent call last):
  File "./preprocess.py", line 67, in <module>
    dfTrain = dfTrain.apply(clean, axis=1)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.16.2-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 3718, in apply
    return self._apply_standard(f, axis, reduce=reduce)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.16.2-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 3808, in _apply_standard
    results[i] = func(v)
  File "./preprocess.py", line 66, in <lambda>
    clean = lambda line: clean_text(line, drop_html_flag=config.drop_html_flag)
  File "/home/zhouge/software/tool/kaggle/Kaggle_CrowdFlower/Code/Feat/nlp_utils.py", line 184, in clean_text
    l = drop_html(l)
  File "/home/zhouge/software/tool/kaggle/Kaggle_CrowdFlower/Code/Feat/nlp_utils.py", line 211, in drop_html
    return BeautifulSoup(html).get_text(separator=" ")
TypeError: ("'NoneType' object is not callable", u'occurred at index 0')
Traceback (most recent call last):
  File "./genFeat_id_feat.py", line 35, in <module>
    with open(config.processed_train_data_path, "rb") as f:
IOError: [Errno 2] No such file or directory: '../../Feat/solution/train.processed.csv.pkl'
Traceback (most recent call last):
  File "./genFeat_counting_feat.py", line 171, in <module>
    with open(config.processed_train_data_path, "rb") as f:
IOError: [Errno 2] No such file or directory: '../../Feat/solution/train.processed.csv.pkl'
Traceback (most recent call last):
  File "./genFeat_distance_feat.py", line 235, in <module>
    with open(config.processed_train_data_path, "rb") as f:
IOError: [Errno 2] No such file or directory: '../../Feat/solution/train.processed.csv.pkl'
Traceback (most recent call last):
  File "./genFeat_basic_tfidf_feat.py", line 46, in <module>
    from sklearn.manifold import TSNE
ImportError: cannot import name TSNE
Traceback (most recent call last):
  File "./genFeat_cooccurrence_tfidf_feat.py", line 144, in <module>
    with open(config.processed_train_data_path, "rb") as f:
IOError: [Errno 2] No such file or directory: '../../Feat/solution/train.processed.csv.pkl'
Traceback (most recent call last):
  File "./combine_feat_[LSA_and_stats_feat_Jun09]_[Low].py", line 387, in <module>
    gen_info(feat_path_name="LSA_and_stats_feat_Jun09")
  File "/home/zhouge/software/tool/kaggle/Kaggle_CrowdFlower/Code/Feat/gen_info.py", line 38, in gen_info
    with open(config.processed_train_data_path, "rb") as f:
IOError: [Errno 2] No such file or directory: '../../Feat/solution/train.processed.csv.pkl'
Traceback (most recent call last):
  File "./combine_feat_[LSA_svd150_and_Jaccard_coef_Jun14]_[Low].py", line 387, in <module>
    gen_info(feat_path_name="LSA_svd150_and_Jaccard_coef_Jun14")
  File "/home/zhouge/software/tool/kaggle/Kaggle_CrowdFlower/Code/Feat/gen_info.py", line 38, in gen_info
    with open(config.processed_train_data_path, "rb") as f:
IOError: [Errno 2] No such file or directory: '../../Feat/solution/train.processed.csv.pkl'
Traceback (most recent call last):
  File "./combine_feat_[svd100_and_bow_Jun23]_[Low].py", line 391, in <module>
    gen_info(feat_path_name="svd100_and_bow_Jun23")
  File "/home/zhouge/software/tool/kaggle/Kaggle_CrowdFlower/Code/Feat/gen_info.py", line 38, in gen_info
    with open(config.processed_train_data_path, "rb") as f:
IOError: [Errno 2] No such file or directory: '../../Feat/solution/train.processed.csv.pkl'
Traceback (most recent call last):
  File "./combine_feat_[svd100_and_bow_Jun27]_[High].py", line 437, in <module>
    gen_info(feat_path_name="svd100_and_bow_Jun27")
  File "/home/zhouge/software/tool/kaggle/Kaggle_CrowdFlower/Code/Feat/gen_info.py", line 38, in gen_info
    with open(config.processed_train_data_path, "rb") as f:
IOError: [Errno 2] No such file or directory: '../../Feat/solution/train.processed.csv.pkl'

**Comment by ChenglongChen** [comment]
Not very sure about what causes this. But apparently, the pre-processed file, i.e., "train.processed.csv.pkl", hasn't been correctly generated. Can you re-intall the BeautifulSoup package to see if that fixes the problem. I am using bs4 4.3.2. If the problem continues, try disabling the drop_html function call by setting drop_html_flag in the param_config.py to False.
